// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xl-v1-metadata.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XlMetaV1_VersionType int32

const (
	XlMetaV1_V100 XlMetaV1_VersionType = 0
	XlMetaV1_V101 XlMetaV1_VersionType = 1
)

var XlMetaV1_VersionType_name = map[int32]string{
	0: "V100",
	1: "V101",
}

var XlMetaV1_VersionType_value = map[string]int32{
	"V100": 0,
	"V101": 1,
}

func (x XlMetaV1_VersionType) String() string {
	return proto.EnumName(XlMetaV1_VersionType_name, int32(x))
}

func (XlMetaV1_VersionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 0}
}

type XlMetaV1_FormatType int32

const (
	XlMetaV1_XL XlMetaV1_FormatType = 0
)

var XlMetaV1_FormatType_name = map[int32]string{
	0: "XL",
}

var XlMetaV1_FormatType_value = map[string]int32{
	"XL": 0,
}

func (x XlMetaV1_FormatType) String() string {
	return proto.EnumName(XlMetaV1_FormatType_name, int32(x))
}

func (XlMetaV1_FormatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 1}
}

type XlMetaV1_AlgorithmType int32

const (
	XlMetaV1_ErasureAlgorithmKlauspost XlMetaV1_AlgorithmType = 0
)

var XlMetaV1_AlgorithmType_name = map[int32]string{
	0: "ErasureAlgorithmKlauspost",
}

var XlMetaV1_AlgorithmType_value = map[string]int32{
	"ErasureAlgorithmKlauspost": 0,
}

func (x XlMetaV1_AlgorithmType) String() string {
	return proto.EnumName(XlMetaV1_AlgorithmType_name, int32(x))
}

func (XlMetaV1_AlgorithmType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 2}
}

type ObjectPartInfoType struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Etag                 string   `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ActualSize           int64    `protobuf:"varint,5,opt,name=actualSize,proto3" json:"actualSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPartInfoType) Reset()         { *m = ObjectPartInfoType{} }
func (m *ObjectPartInfoType) String() string { return proto.CompactTextString(m) }
func (*ObjectPartInfoType) ProtoMessage()    {}
func (*ObjectPartInfoType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{0}
}

func (m *ObjectPartInfoType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPartInfoType.Unmarshal(m, b)
}
func (m *ObjectPartInfoType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPartInfoType.Marshal(b, m, deterministic)
}
func (m *ObjectPartInfoType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPartInfoType.Merge(m, src)
}
func (m *ObjectPartInfoType) XXX_Size() int {
	return xxx_messageInfo_ObjectPartInfoType.Size(m)
}
func (m *ObjectPartInfoType) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPartInfoType.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPartInfoType proto.InternalMessageInfo

func (m *ObjectPartInfoType) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ObjectPartInfoType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectPartInfoType) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ObjectPartInfoType) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjectPartInfoType) GetActualSize() int64 {
	if m != nil {
		return m.ActualSize
	}
	return 0
}

type XlMetaV1 struct {
	Version              XlMetaV1_VersionType      `protobuf:"varint,1,opt,name=version,proto3,enum=pb.XlMetaV1_VersionType" json:"version,omitempty"`
	Format               XlMetaV1_FormatType       `protobuf:"varint,2,opt,name=format,proto3,enum=pb.XlMetaV1_FormatType" json:"format,omitempty"`
	Stat                 *XlMetaV1_StatInfo        `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	Erasure              *XlMetaV1_ErasureInfoType `protobuf:"bytes,4,opt,name=erasure,proto3" json:"erasure,omitempty"`
	Minio                *XlMetaV1_MinioType       `protobuf:"bytes,5,opt,name=minio,proto3" json:"minio,omitempty"`
	Meta                 map[string]string         `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Parts                []*ObjectPartInfoType     `protobuf:"bytes,7,rep,name=Parts,proto3" json:"Parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *XlMetaV1) Reset()         { *m = XlMetaV1{} }
func (m *XlMetaV1) String() string { return proto.CompactTextString(m) }
func (*XlMetaV1) ProtoMessage()    {}
func (*XlMetaV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1}
}

func (m *XlMetaV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XlMetaV1.Unmarshal(m, b)
}
func (m *XlMetaV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XlMetaV1.Marshal(b, m, deterministic)
}
func (m *XlMetaV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XlMetaV1.Merge(m, src)
}
func (m *XlMetaV1) XXX_Size() int {
	return xxx_messageInfo_XlMetaV1.Size(m)
}
func (m *XlMetaV1) XXX_DiscardUnknown() {
	xxx_messageInfo_XlMetaV1.DiscardUnknown(m)
}

var xxx_messageInfo_XlMetaV1 proto.InternalMessageInfo

func (m *XlMetaV1) GetVersion() XlMetaV1_VersionType {
	if m != nil {
		return m.Version
	}
	return XlMetaV1_V100
}

func (m *XlMetaV1) GetFormat() XlMetaV1_FormatType {
	if m != nil {
		return m.Format
	}
	return XlMetaV1_XL
}

func (m *XlMetaV1) GetStat() *XlMetaV1_StatInfo {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *XlMetaV1) GetErasure() *XlMetaV1_ErasureInfoType {
	if m != nil {
		return m.Erasure
	}
	return nil
}

func (m *XlMetaV1) GetMinio() *XlMetaV1_MinioType {
	if m != nil {
		return m.Minio
	}
	return nil
}

func (m *XlMetaV1) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *XlMetaV1) GetParts() []*ObjectPartInfoType {
	if m != nil {
		return m.Parts
	}
	return nil
}

type XlMetaV1_StatInfo struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	ModTime              int64    `protobuf:"varint,2,opt,name=modTime,proto3" json:"modTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XlMetaV1_StatInfo) Reset()         { *m = XlMetaV1_StatInfo{} }
func (m *XlMetaV1_StatInfo) String() string { return proto.CompactTextString(m) }
func (*XlMetaV1_StatInfo) ProtoMessage()    {}
func (*XlMetaV1_StatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 0}
}

func (m *XlMetaV1_StatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XlMetaV1_StatInfo.Unmarshal(m, b)
}
func (m *XlMetaV1_StatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XlMetaV1_StatInfo.Marshal(b, m, deterministic)
}
func (m *XlMetaV1_StatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XlMetaV1_StatInfo.Merge(m, src)
}
func (m *XlMetaV1_StatInfo) XXX_Size() int {
	return xxx_messageInfo_XlMetaV1_StatInfo.Size(m)
}
func (m *XlMetaV1_StatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_XlMetaV1_StatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_XlMetaV1_StatInfo proto.InternalMessageInfo

func (m *XlMetaV1_StatInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *XlMetaV1_StatInfo) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

type XlMetaV1_ErasureInfoType struct {
	Algorithm            XlMetaV1_AlgorithmType                       `protobuf:"varint,1,opt,name=algorithm,proto3,enum=pb.XlMetaV1_AlgorithmType" json:"algorithm,omitempty"`
	DataBlocks           int32                                        `protobuf:"varint,2,opt,name=dataBlocks,proto3" json:"dataBlocks,omitempty"`
	ParityBlocks         int32                                        `protobuf:"varint,3,opt,name=parityBlocks,proto3" json:"parityBlocks,omitempty"`
	BlockSize            int64                                        `protobuf:"varint,4,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	Index                int32                                        `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Distribution         []int32                                      `protobuf:"varint,6,rep,packed,name=distribution,proto3" json:"distribution,omitempty"`
	Checksums            []*XlMetaV1_ErasureInfoType_ChecksumInfoType `protobuf:"bytes,7,rep,name=checksums,proto3" json:"checksums,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *XlMetaV1_ErasureInfoType) Reset()         { *m = XlMetaV1_ErasureInfoType{} }
func (m *XlMetaV1_ErasureInfoType) String() string { return proto.CompactTextString(m) }
func (*XlMetaV1_ErasureInfoType) ProtoMessage()    {}
func (*XlMetaV1_ErasureInfoType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 1}
}

func (m *XlMetaV1_ErasureInfoType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType.Unmarshal(m, b)
}
func (m *XlMetaV1_ErasureInfoType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType.Marshal(b, m, deterministic)
}
func (m *XlMetaV1_ErasureInfoType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XlMetaV1_ErasureInfoType.Merge(m, src)
}
func (m *XlMetaV1_ErasureInfoType) XXX_Size() int {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType.Size(m)
}
func (m *XlMetaV1_ErasureInfoType) XXX_DiscardUnknown() {
	xxx_messageInfo_XlMetaV1_ErasureInfoType.DiscardUnknown(m)
}

var xxx_messageInfo_XlMetaV1_ErasureInfoType proto.InternalMessageInfo

func (m *XlMetaV1_ErasureInfoType) GetAlgorithm() XlMetaV1_AlgorithmType {
	if m != nil {
		return m.Algorithm
	}
	return XlMetaV1_ErasureAlgorithmKlauspost
}

func (m *XlMetaV1_ErasureInfoType) GetDataBlocks() int32 {
	if m != nil {
		return m.DataBlocks
	}
	return 0
}

func (m *XlMetaV1_ErasureInfoType) GetParityBlocks() int32 {
	if m != nil {
		return m.ParityBlocks
	}
	return 0
}

func (m *XlMetaV1_ErasureInfoType) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *XlMetaV1_ErasureInfoType) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *XlMetaV1_ErasureInfoType) GetDistribution() []int32 {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (m *XlMetaV1_ErasureInfoType) GetChecksums() []*XlMetaV1_ErasureInfoType_ChecksumInfoType {
	if m != nil {
		return m.Checksums
	}
	return nil
}

type XlMetaV1_ErasureInfoType_ChecksumInfoType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Algorithm            int32    `protobuf:"varint,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) Reset() {
	*m = XlMetaV1_ErasureInfoType_ChecksumInfoType{}
}
func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) String() string { return proto.CompactTextString(m) }
func (*XlMetaV1_ErasureInfoType_ChecksumInfoType) ProtoMessage()    {}
func (*XlMetaV1_ErasureInfoType_ChecksumInfoType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 1, 0}
}

func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType.Unmarshal(m, b)
}
func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType.Marshal(b, m, deterministic)
}
func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType.Merge(m, src)
}
func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) XXX_Size() int {
	return xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType.Size(m)
}
func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) XXX_DiscardUnknown() {
	xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType.DiscardUnknown(m)
}

var xxx_messageInfo_XlMetaV1_ErasureInfoType_ChecksumInfoType proto.InternalMessageInfo

func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) GetAlgorithm() int32 {
	if m != nil {
		return m.Algorithm
	}
	return 0
}

func (m *XlMetaV1_ErasureInfoType_ChecksumInfoType) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type XlMetaV1_MinioType struct {
	Release              string   `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XlMetaV1_MinioType) Reset()         { *m = XlMetaV1_MinioType{} }
func (m *XlMetaV1_MinioType) String() string { return proto.CompactTextString(m) }
func (*XlMetaV1_MinioType) ProtoMessage()    {}
func (*XlMetaV1_MinioType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f57604e38abbeb71, []int{1, 2}
}

func (m *XlMetaV1_MinioType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XlMetaV1_MinioType.Unmarshal(m, b)
}
func (m *XlMetaV1_MinioType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XlMetaV1_MinioType.Marshal(b, m, deterministic)
}
func (m *XlMetaV1_MinioType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XlMetaV1_MinioType.Merge(m, src)
}
func (m *XlMetaV1_MinioType) XXX_Size() int {
	return xxx_messageInfo_XlMetaV1_MinioType.Size(m)
}
func (m *XlMetaV1_MinioType) XXX_DiscardUnknown() {
	xxx_messageInfo_XlMetaV1_MinioType.DiscardUnknown(m)
}

var xxx_messageInfo_XlMetaV1_MinioType proto.InternalMessageInfo

func (m *XlMetaV1_MinioType) GetRelease() string {
	if m != nil {
		return m.Release
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.XlMetaV1_VersionType", XlMetaV1_VersionType_name, XlMetaV1_VersionType_value)
	proto.RegisterEnum("pb.XlMetaV1_FormatType", XlMetaV1_FormatType_name, XlMetaV1_FormatType_value)
	proto.RegisterEnum("pb.XlMetaV1_AlgorithmType", XlMetaV1_AlgorithmType_name, XlMetaV1_AlgorithmType_value)
	proto.RegisterType((*ObjectPartInfoType)(nil), "pb.ObjectPartInfoType")
	proto.RegisterType((*XlMetaV1)(nil), "pb.xlMetaV1")
	proto.RegisterMapType((map[string]string)(nil), "pb.xlMetaV1.MetaEntry")
	proto.RegisterType((*XlMetaV1_StatInfo)(nil), "pb.xlMetaV1.StatInfo")
	proto.RegisterType((*XlMetaV1_ErasureInfoType)(nil), "pb.xlMetaV1.ErasureInfoType")
	proto.RegisterType((*XlMetaV1_ErasureInfoType_ChecksumInfoType)(nil), "pb.xlMetaV1.ErasureInfoType.ChecksumInfoType")
	proto.RegisterType((*XlMetaV1_MinioType)(nil), "pb.xlMetaV1.MinioType")
}

func init() { proto.RegisterFile("xl-v1-metadata.proto", fileDescriptor_f57604e38abbeb71) }

var fileDescriptor_f57604e38abbeb71 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x6d, 0x36, 0xc9, 0x6e, 0x73, 0xb7, 0xd6, 0x30, 0xd4, 0x1a, 0x43, 0x95, 0x35, 0x20, 0x54,
	0xb1, 0xb1, 0x1b, 0x41, 0x8b, 0x6f, 0x2a, 0x15, 0xa4, 0x16, 0x65, 0x5a, 0x4a, 0x5f, 0x27, 0xbb,
	0xd3, 0x6e, 0xdc, 0x7c, 0x31, 0x33, 0x59, 0x76, 0xfd, 0x05, 0x3e, 0xf9, 0x53, 0xfd, 0x0d, 0x32,
	0x93, 0xef, 0x16, 0x7c, 0xbb, 0xf7, 0x9e, 0x33, 0x93, 0x3b, 0xe7, 0xdc, 0x1b, 0xd8, 0x5b, 0xc7,
	0x47, 0xab, 0xe9, 0x51, 0x42, 0x05, 0x99, 0x13, 0x41, 0xfc, 0x9c, 0x65, 0x22, 0x43, 0x83, 0x3c,
	0xf4, 0x7e, 0x6b, 0x80, 0xbe, 0x87, 0x3f, 0xe9, 0x4c, 0xfc, 0x20, 0x4c, 0x7c, 0x4d, 0x6f, 0xb2,
	0xcb, 0x4d, 0x4e, 0xd1, 0x3e, 0x0c, 0xd3, 0x22, 0x09, 0x29, 0x73, 0xb4, 0x89, 0x76, 0x68, 0xe2,
	0x2a, 0x43, 0x08, 0x8c, 0x94, 0x24, 0xd4, 0x19, 0x4c, 0xb4, 0x43, 0x0b, 0xab, 0x58, 0xd6, 0xa8,
	0x20, 0xb7, 0x8e, 0x5e, 0xd6, 0x64, 0x2c, 0x6b, 0x3c, 0xfa, 0x45, 0x1d, 0x63, 0xa2, 0x1d, 0xea,
	0x58, 0xc5, 0xe8, 0x19, 0x00, 0x99, 0x89, 0x82, 0xc4, 0x17, 0x12, 0x31, 0x15, 0xd2, 0xa9, 0x78,
	0x7f, 0x47, 0xb0, 0xbd, 0x8e, 0xcf, 0xa9, 0x20, 0x57, 0x53, 0x14, 0xc0, 0x68, 0x45, 0x19, 0x8f,
	0xb2, 0x54, 0x75, 0xb0, 0x1b, 0x38, 0x7e, 0x1e, 0xfa, 0x35, 0xec, 0x5f, 0x95, 0x98, 0xec, 0x15,
	0xd7, 0x44, 0xf4, 0x06, 0x86, 0x37, 0x19, 0x4b, 0x88, 0x50, 0xed, 0xed, 0x06, 0x8f, 0x7b, 0x47,
	0xbe, 0x28, 0x48, 0x9d, 0xa8, 0x68, 0xe8, 0x25, 0x18, 0x5c, 0x10, 0xa1, 0x3a, 0x1f, 0x07, 0x8f,
	0x7a, 0xf4, 0x0b, 0x41, 0x94, 0x1c, 0x58, 0x51, 0xd0, 0x3b, 0x18, 0x51, 0x46, 0x78, 0xc1, 0xca,
	0x37, 0x8d, 0x83, 0x83, 0x1e, 0xfb, 0xb4, 0xc4, 0x6a, 0xfd, 0x70, 0x4d, 0x46, 0xaf, 0xc1, 0x4c,
	0xa2, 0x34, 0xca, 0xd4, 0x7b, 0xc7, 0xc1, 0x7e, 0xef, 0xd4, 0xb9, 0x44, 0x14, 0xbf, 0x24, 0xa1,
	0x57, 0x60, 0x48, 0x8f, 0x9c, 0xe1, 0x44, 0xbf, 0x4f, 0xa6, 0x82, 0x9c, 0xa6, 0x82, 0x6d, 0xb0,
	0xe2, 0xc8, 0x9b, 0xa5, 0x65, 0xdc, 0x19, 0xb5, 0xe4, 0xfb, 0x4e, 0xe2, 0x92, 0xe4, 0x9e, 0xc0,
	0x76, 0xfd, 0xa2, 0xc6, 0x1c, 0xad, 0x63, 0x8e, 0x03, 0xa3, 0x24, 0x9b, 0x5f, 0x46, 0x95, 0xb7,
	0x3a, 0xae, 0x53, 0xf7, 0x8f, 0x0e, 0x0f, 0xef, 0x3c, 0x0f, 0x9d, 0x80, 0x45, 0xe2, 0xdb, 0x8c,
	0x45, 0x62, 0x91, 0x54, 0xfe, 0xb8, 0xbd, 0x66, 0x3f, 0xd6, 0xa8, 0xea, 0xa1, 0x25, 0xcb, 0x21,
	0x90, 0x13, 0xf8, 0x29, 0xce, 0x66, 0x4b, 0xae, 0x3e, 0x65, 0xe2, 0x4e, 0x05, 0x79, 0xb0, 0x93,
	0x13, 0x16, 0x89, 0x4d, 0xc5, 0xd0, 0x15, 0xa3, 0x57, 0x43, 0x07, 0x60, 0x85, 0x32, 0xba, 0x68,
	0x27, 0xac, 0x2d, 0xa0, 0x3d, 0x30, 0xa3, 0x74, 0x4e, 0xd7, 0x4a, 0x71, 0x13, 0x97, 0x89, 0xbc,
	0x77, 0x1e, 0x71, 0xc1, 0xa2, 0xb0, 0x10, 0x72, 0xa8, 0xa4, 0xc2, 0x26, 0xee, 0xd5, 0xd0, 0x19,
	0x58, 0xb3, 0x05, 0x9d, 0x2d, 0x79, 0x91, 0xd4, 0xaa, 0x1e, 0xfd, 0xcf, 0x65, 0xff, 0x73, 0xc5,
	0x6e, 0xc4, 0x6e, 0xcf, 0xbb, 0xd7, 0x60, 0xdf, 0x85, 0x9b, 0xed, 0xd1, 0x3a, 0xdb, 0x73, 0xd0,
	0x95, 0xb2, 0xd4, 0xa3, 0x23, 0x17, 0x02, 0x63, 0x41, 0xf8, 0x42, 0xc9, 0xb0, 0x83, 0x55, 0xec,
	0xbe, 0x00, 0xab, 0x19, 0x1c, 0xe9, 0x1b, 0xa3, 0x31, 0x25, 0xbc, 0xbe, 0xb5, 0x4e, 0xdd, 0xf7,
	0x60, 0x35, 0x23, 0x83, 0x6c, 0xd0, 0x97, 0x74, 0x53, 0x51, 0x64, 0x28, 0x65, 0x5a, 0x91, 0xb8,
	0xa8, 0x57, 0xb9, 0x4c, 0x3e, 0x0c, 0x4e, 0x34, 0xef, 0x39, 0x8c, 0x3b, 0xeb, 0x85, 0xb6, 0xc1,
	0xb8, 0x9a, 0x1e, 0x1f, 0xdb, 0x5b, 0x55, 0x34, 0xb5, 0x35, 0x6f, 0x0f, 0xa0, 0x5d, 0x27, 0x34,
	0x84, 0xc1, 0xf5, 0x37, 0x7b, 0xcb, 0xf3, 0xe1, 0x41, 0xcf, 0x77, 0xf4, 0x14, 0x9e, 0x54, 0x92,
	0x35, 0xf5, 0xb3, 0x98, 0x14, 0x3c, 0xcf, 0xb8, 0xb0, 0xb7, 0xc2, 0xa1, 0xfa, 0x0d, 0xbd, 0xfd,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x86, 0x2e, 0xd3, 0x3a, 0x9e, 0x04, 0x00, 0x00,
}
